# Generated by Django 5.2.4 on 2025-08-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_flat_owner_remove_flat_owners_phonenumber_and_more'),
        ('property', '0014_auto_20250722_2040'),
    ]

    operations = [
    ]
